
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-credentials=true
      - http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE
      - http.cors.allow-headers=X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization

    
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  crawler:
    build: ./crawler
    container_name: crawler
    volumes:
      - /mnt/sharevm1:/app/data:ro
      - crawler_state:/app/state
    env_file:
      - ./crawler/.env
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch

  theharvester_api:
    build: ./theharvester_api
    container_name: theharvester_api
    ports:
      - "5100:5100"
    restart: unless-stopped
    volumes:
      - ./api-keys.yaml:/root/.theHarvester/api-keys.yaml
      - ./api-keys.yaml:/etc/theHarvester/api-keys.yaml
      
  social_scraper:
    build: ./social_scraper
    container_name: social_scraper
    ports:
      - "5200:5200"
    volumes:
      - ./api-keys.yaml:/app/api-keys.yaml
    depends_on:
      - elasticsearch

  mailer:
    build: ./mailer
    container_name: mailer
    depends_on:
      - elasticsearch
    env_file:
      - ./mailer/.env   # credentials stored here
    restart: unless-stopped
    volumes:
      - ./mailer/keywords.txt:/app/keywords.txt
      - ./mailer/blacklist.txt:/app/blacklist.txt


  telegram_bot:
    build: ./telegram_bot
    container_name: telegram_bot
    ports:
      - "6000:6000"
    env_file:
      - ./telegram_bot/.env
    restart: unless-stopped
    depends_on:
      - elasticsearch
     
    volumes:
      - ./telegram_bot/sessions:/app/sessions 

volumes:
  esdata:
  crawler_state:
